PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\agplog.h \
 $(MC_SOURCEDIR)\agplog.rc \


386_OBJECTS=\
 $(OBJ_PATH)\$O\init.obj \
 $(OBJ_PATH)\$O\gart.obj \
 $(OBJ_PATH)\$O\verifier.obj \


_RES_FILE=$(OBJ_PATH)\$O\uagp35.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\kernel\agp\uagp35
MAKEDIR_RELATIVE_TO_BASEDIR=src\kernel\agp\uagp35
OBJ_PATH=e:\sdk\wdk_6001\src\kernel\agp\uagp35
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
