PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\softusbloopback.h \


386_OBJECTS=\
 $(OBJ_PATH)\$O\loopbackdevice.obj \
 $(OBJ_PATH)\$O\softusbloopback.obj \


_RES_FILE=$(OBJ_PATH)\$O\softusbloopback.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\test\dsf\usb\softusbloopback
MAKEDIR_RELATIVE_TO_BASEDIR=src\test\dsf\usb\softusbloopback
OBJ_PATH=e:\sdk\wdk_6001\src\test\dsf\usb\softusbloopback
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
