

386_OBJECTS=\
 $(OBJ_PATH)\$O\device.obj \
 $(OBJ_PATH)\$O\filter.obj \
 $(OBJ_PATH)\$O\pin.obj \


_RES_FILE=$(OBJ_PATH)\$O\gfx.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\audio\gfxswap.xp\driver
MAKEDIR_RELATIVE_TO_BASEDIR=src\audio\gfxswap.xp\driver
OBJ_PATH=e:\sdk\wdk_6001\src\audio\gfxswap.xp\driver
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
