PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\msg.h \
 $(MC_SOURCEDIR)\msg.rc \


386_OBJECTS=\
 $(OBJ_PATH)\$O\init.obj \


_RES_FILE=$(OBJ_PATH)\$O\pciide.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\storage\miniide\pciide
MAKEDIR_RELATIVE_TO_BASEDIR=src\storage\miniide\pciide
OBJ_PATH=e:\sdk\wdk_6001\src\storage\miniide\pciide
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
