PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\softhiddevice.h \


386_OBJECTS=\
 $(OBJ_PATH)\$O\softhiddevice_i.obj \
 $(OBJ_PATH)\$O\softhiddevice.obj \
 $(OBJ_PATH)\$O\softhid.obj \
 $(OBJ_PATH)\$O\softhidinputkbdmapper.obj \
 $(OBJ_PATH)\$O\messagetask.obj \
 $(OBJ_PATH)\$O\task.obj \


_RES_FILE=$(OBJ_PATH)\$O\softhiddevice.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\test\dsf\usb\softhiddevice
MAKEDIR_RELATIVE_TO_BASEDIR=src\test\dsf\usb\softhiddevice
OBJ_PATH=e:\sdk\wdk_6001\src\test\dsf\usb\softhiddevice
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
