#ifndef _MULTIENGINEH_
#define _MULTIENGINEH_

#define DONOT_USE_VIDEO_ENGINE
//#define USE_LOCK_TO_SYNC_ENGINES

#define MULTI_ENGINE_NODE_3D        0
#define MULTI_ENGINE_NODE_VIDEO     1

#define MULTI_ENGINE_COUNT          2


#endif // _MULTIENGINEH_
