

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\1394diag.obj \
 $(OBJ_PATH)\$O\ioctl.obj \
 $(OBJ_PATH)\$O\pnp.obj \
 $(OBJ_PATH)\$O\power.obj \


_RES_FILE=$(OBJ_PATH)\$O\1394diag.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\1394\driver\1394diag
MAKEDIR_RELATIVE_TO_BASEDIR=src\1394\driver\1394diag
OBJ_PATH=e:\sdk\wdk_6001\src\1394\driver\1394diag
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
