PASS0_AMD64_OBJECTS=\
 $(PASS0_HEADERDIR)\gfxprop.h \


AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\gfxprop.obj \
 $(OBJ_PATH)\$O\gfxproperty.obj \
 $(OBJ_PATH)\$O\gfxproppages.obj \


_RES_FILE=$(OBJ_PATH)\$O\gfxprop.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\audio\gfxswap.xp\gfxprop
MAKEDIR_RELATIVE_TO_BASEDIR=src\audio\gfxswap.xp\gfxprop
OBJ_PATH=e:\sdk\wdk_6001\src\audio\gfxswap.xp\gfxprop
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
