#ifndef _RADEON_H_
#define _RADEON_H_

// 0x100 - Radeon 1 (Rage 6)
// 0x200 - Radeon 2 (Chaplin/Rage6x/Rage7)
#ifndef RADEON_ASIC
#define RADEON_ASIC 0x100
#endif


#ifdef	DEFAULT_PITCH
// Apparently Microsoft defines the symbol DEFAULT_PITCH someplace,
// but this is the name of a field in one of the registers.  This conflict
// shows up in bf_func.h.  Since this is autogenerated, it is better
// to get rid of the Microsoft definition here, since we don't need
// it anyway.
#undef  DEFAULT_PITCH
#endif



// Include the appropriate ASIC header files

#if (RADEON_ASIC < 0x300) // Radeon2/Chaplin/Rage6X

#include "radeon2\chaplin_mask.h"
#include "radeon2\chaplin_offset.h"
#include "radeon2\chaplin_shift.h"
#include "radeon2\chaplin_enum.h"
#include "radeonLegacyDefs.h"     // Chaplin TODO:  remove this.

#endif // Radeon Builds


#endif // _RADEON_H_
