#ifndef _RADEON_BFFUNC_H_
#define _RADEON_BFFUNC_H_

#include "radeon.h"

#ifdef	DEFAULT_PITCH
// Apparently Microsoft defines the symbol DEFAULT_PITCH someplace,
// but this is the name of a field in one of the registers.  This conflict
// shows up in bf_func.h.  Since this is autogenerated, it is better
// to get rid of the Microsoft definition here, since we don't need
// it anyway.
#undef  DEFAULT_PITCH
#endif

// Include the appropriate bf_func.h
#if (RADEON_ASIC < 0x300) // Radeon2/Chaplin/Rage6X
#pragma warning(disable: 4049)
#include "chaplin_bf_func.h"
#pragma warning(default: 4049)
#endif // Radeon Builds

#endif // _RADEON_BFFUNC_H_
