

386_OBJECTS=\
 $(OBJ_PATH)\$O\adapter.obj \
 $(OBJ_PATH)\$O\common.obj \
 $(OBJ_PATH)\$O\mintopo.obj \
 $(OBJ_PATH)\$O\minwave.obj \


_RES_FILE=$(OBJ_PATH)\$O\sb16.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\audio\sb16
MAKEDIR_RELATIVE_TO_BASEDIR=src\audio\sb16
OBJ_PATH=e:\sdk\wdk_6001\src\audio\sb16
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
