

386_OBJECTS=\
 $(OBJ_PATH)\$O\driver.obj \
 $(OBJ_PATH)\$O\device.obj \
 $(OBJ_PATH)\$O\client.obj \
 $(OBJ_PATH)\$O\queue.obj \





# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\bth\bthecho\bthcli\sys
MAKEDIR_RELATIVE_TO_BASEDIR=src\bth\bthecho\bthcli\sys
OBJ_PATH=e:\sdk\wdk_6001\src\bth\bthecho\bthcli\sys
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
