PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\kbdlog.h \
 $(MC_SOURCEDIR)\kbdlog.rc \


386_OBJECTS=\
 $(OBJ_PATH)\$O\kbdclass.obj \


_RES_FILE=$(OBJ_PATH)\$O\kbdclass.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\input\kbdclass
MAKEDIR_RELATIVE_TO_BASEDIR=src\input\kbdclass
OBJ_PATH=e:\sdk\wdk_6001\src\input\kbdclass
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
