

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\1394api.obj \
 $(OBJ_PATH)\$O\1394main.obj \
 $(OBJ_PATH)\$O\asyncapi.obj \
 $(OBJ_PATH)\$O\debug.obj \
 $(OBJ_PATH)\$O\isochapi.obj \
 $(OBJ_PATH)\$O\util.obj \


_RES_FILE=$(OBJ_PATH)\$O\1394api.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\1394\dll\1394api
MAKEDIR_RELATIVE_TO_BASEDIR=src\1394\dll\1394api
OBJ_PATH=e:\sdk\wdk_6001\src\1394\dll\1394api
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
