PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\clonehelper.h \


386_OBJECTS=\
 $(OBJ_PATH)\$O\clonehelperimpl.obj \
 $(OBJ_PATH)\$O\streamhelper.obj \


_RES_FILE=$(OBJ_PATH)\$O\clonehelper.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\video\r200sample\clone
MAKEDIR_RELATIVE_TO_BASEDIR=src\video\r200sample\clone
OBJ_PATH=e:\sdk\wdk_6001\src\video\r200sample\clone
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
