

386_OBJECTS=\
 $(OBJ_PATH)\$O\toaster.obj \
 $(OBJ_PATH)\$O\power.obj \
 $(OBJ_PATH)\$O\wmi.obj \


_RES_FILE=$(OBJ_PATH)\$O\toaster.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\kmdf\toaster\func\featured
MAKEDIR_RELATIVE_TO_BASEDIR=src\kmdf\toaster\func\featured
OBJ_PATH=e:\sdk\wdk_6001\src\kmdf\toaster\func\featured
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
