

386_OBJECTS=\
 $(OBJ_PATH)\$O\sdp.obj \
 $(OBJ_PATH)\$O\server.obj \
 $(OBJ_PATH)\$O\driver.obj \
 $(OBJ_PATH)\$O\device.obj \
 $(OBJ_PATH)\$O\echo.obj \





# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\bth\bthecho\bthsrv\sys
MAKEDIR_RELATIVE_TO_BASEDIR=src\bth\bthecho\bthsrv\sys
OBJ_PATH=e:\sdk\wdk_6001\src\bth\bthecho\bthsrv\sys
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
