PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\softusbaudio.h \


386_OBJECTS=\
 $(OBJ_PATH)\$O\audiodevice.obj \
 $(OBJ_PATH)\$O\softusbaudio.obj \


_RES_FILE=$(OBJ_PATH)\$O\softusbaudio.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\test\dsf\usb\softusbaudio
MAKEDIR_RELATIVE_TO_BASEDIR=src\test\dsf\usb\softusbaudio
OBJ_PATH=e:\sdk\wdk_6001\src\test\dsf\usb\softusbaudio
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
