

386_OBJECTS=\
 $(OBJ_PATH)\$O\bulkusb.obj \
 $(OBJ_PATH)\$O\bulkpnp.obj \
 $(OBJ_PATH)\$O\bulkpwr.obj \
 $(OBJ_PATH)\$O\bulkdev.obj \
 $(OBJ_PATH)\$O\bulkwmi.obj \
 $(OBJ_PATH)\$O\bulkrwr.obj \


_RES_FILE=$(OBJ_PATH)\$O\bulkusb.res



# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\usb\bulkusb\sys
MAKEDIR_RELATIVE_TO_BASEDIR=src\usb\bulkusb\sys
OBJ_PATH=e:\sdk\wdk_6001\src\usb\bulkusb\sys
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
