PASS0_386_OBJECTS=\
 $(PASS0_HEADERDIR)\protnotify.h \


386_OBJECTS=\
 $(OBJ_PATH)\$O\dllmain.obj \
 $(OBJ_PATH)\$O\protnotify.obj \


_RES_FILE=$(OBJ_PATH)\$O\protnotify.res
PRECOMPILED_INCLUDE_BASENAME=common.hpp




# lowercased
BASEDIR=e:\sdk\wdk_6001
OBJECT_ROOT=e:\sdk\wdk_6001
MAKEDIR_LOWERCASE=e:\sdk\wdk_6001\src\kmdf\ndisprot\notifyob
MAKEDIR_RELATIVE_TO_BASEDIR=src\kmdf\ndisprot\notifyob
OBJ_PATH=e:\sdk\wdk_6001\src\kmdf\ndisprot\notifyob
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
