

/****************************************************************************\
* 
*  Module Name    atimcode.h
*  Project        DDL/CWDDECI
*  Device         Any
*
*  Description    Header file for the ATI Message Code Id's
*  
*
*  (c) 2001 ATI Technologies Inc. (unpublished)
*
*	 All rights reserved.
*	 The year included in the foregoing notice is the year of creation of the work.
*
*
*
*  LOG OF CHANGES
*
*  1.00   7/23/2001  [SPL] - Created File
*
*
\****************************************************************************/
#ifndef _ATIMCODE_H
#define _ATIMCODE_H

//
// ULONG BREAKDOWN ---
// 
#define ATI_MESSAGECODE_MASK                0x00000FFFL
#define ATI_MESSAGECODE_TYPE_MASK           0x0000f000L
#define ATI_MESSAGECODE_COMPONENT_MASK      0x000f0000L

#define ATI_MESSAGECODE_TYPE_GENERAL        0x00000000L
#define ATI_MESSAGECODE_TYPE_ERROR          0x00001000L
#define ATI_MESSAGECODE_TYPE_MESSAGE        0x00001000L
#define ATI_MESSAGECODE_TYPE_ACTION         0x00002000L
#define ATI_MESSAGECODE_TYPE_LOGINFO        0x00003000L
#define ATI_MESSAGECODE_TYPE_GENERIC_MSG    0x00004000L     // ExtEvent Utility will use ATI_MESSAGECODE_MASK portion of 
                                                            // this kind of message as parameter to launch CP app atiprbxx.exe

#define ATI_MESSAGECODE_COMPONENT_DAL       0x00010000L
#define ATI_MESSAGECODE_COMPONENT_GENERIC   0x00020000L

#define ATI_MESSAGECODE_DAL_ERROR_POWERPLAYSETFAILURE \
            ATI_MESSAGECODE_TYPE_ERROR | ATI_MESSAGECODE_COMPONENT_DAL | 1

#define ATI_MESSAGECODE_DAL_MESSAGE_LCDSHOWRESOLUTIONCHANGEMESSAGE \
            ATI_MESSAGECODE_TYPE_MESSAGE | ATI_MESSAGECODE_COMPONENT_DAL | 2

#define ATI_MESSAGECODE_DAL_MESSAGE_CONTROLLERCONFIGCHANGED \
            ATI_MESSAGECODE_TYPE_MESSAGE | ATI_MESSAGECODE_COMPONENT_DAL | 3

#define ATI_MESSAGECODE_DAL_MESSAGE_POWERPLAYSTATECHANGED \
            ATI_MESSAGECODE_TYPE_MESSAGE | ATI_MESSAGECODE_COMPONENT_DAL | 4

#define ATI_MESSAGECODE_DAL_MESSAGE_EVENTPOWERMODEINFOCHANGED \
            ATI_MESSAGECODE_TYPE_MESSAGE | ATI_MESSAGECODE_COMPONENT_DAL | 5

#define ATI_MESSAGECODE_DAL_MESSAGE_EVENTUSERDEVICEPROFILESAVEONLY \
            ATI_MESSAGECODE_TYPE_MESSAGE | ATI_MESSAGECODE_COMPONENT_DAL | 6

#define ATI_MESSAGECODE_DAL_MESSAGE_EVENTUSERDEVICEPROFILESAVEANDAPPLY \
            ATI_MESSAGECODE_TYPE_MESSAGE | ATI_MESSAGECODE_COMPONENT_DAL | 7

#define ATI_MESSAGECODE_DAL_MESSAGE_EVENTAPPLYUSERSELECTEDPROFILE \
            ATI_MESSAGECODE_TYPE_MESSAGE | ATI_MESSAGECODE_COMPONENT_DAL | 8

#define ATI_MESSAGECODE_DAL_GENERAL_POWERPLAYAUTOADJUSTBPP \
            ATI_MESSAGECODE_TYPE_GENERAL | ATI_MESSAGECODE_COMPONENT_DAL | 1

#define ATI_MESSAGECODE_DAL_ACTION_POWERPLAYSET16BPP \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 1

#define ATI_MESSAGECODE_DAL_ACTION_POWERPLAYSET32BPP \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 2

// NEED to send a buffer of type _DEVMODEINFO                         
#define ATI_MESSAGECODE_DAL_ACTION_SETDESKTOPRESOLUTION \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 3

// This one is basicly to refresh the screen
#define ATI_MESSAGECODE_DAL_ACTION_SETSAMEDESKTOPRESOLUTION \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 4

#define ATI_MESSAGECODE_DAL_ACTION_REMOVELARGEDESKTOPFROMPRIMARYADAPTER \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 5

#define ATI_MESSAGECODE_DAL_ACTION_SETCLONEMODE \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 6

#define ATI_MESSAGECODE_DAL_ACTION_POWERPLAYREFRESHNORMALMODE \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 7
						
#define ATI_MESSAGECODE_DAL_ACTION_POWERPLAYREFRESHLOWMODE \
            ATI_MESSAGECODE_TYPE_ACTION | ATI_MESSAGECODE_COMPONENT_DAL | 8

// ---------------------------------------------------------------------------
// Generic message code. ATI_MESSAGECODE_MASK portion of these messages will 
// be sent to atiprbxx.exe directly as command line parameter

#define ATI_MESSAGECODE_GENERIC_MSG_OUT_OF_MEMORY \
            ATI_MESSAGECODE_TYPE_GENERIC_MSG | ATI_MESSAGECODE_COMPONENT_GENERIC | 5

#define ATI_MESSAGECODE_GENERIC_MSG_OVERLAY_THEATER_FAIL_8BPP \
            ATI_MESSAGECODE_TYPE_GENERIC_MSG | ATI_MESSAGECODE_COMPONENT_GENERIC | 12

// ---------------------------------------------------------------------------
// Note: The following definitions are for MV7 Log Information usage only !!!

#define ATI_MESSAGECODE_DAL_LOGINFO_1 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 1
#define ATI_MESSAGECODE_DAL_LOGINFO_2 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 2
#define ATI_MESSAGECODE_DAL_LOGINFO_3 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 3
#define ATI_MESSAGECODE_DAL_LOGINFO_4 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 4
#define ATI_MESSAGECODE_DAL_LOGINFO_5 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 5
#define ATI_MESSAGECODE_DAL_LOGINFO_6 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 6
#define ATI_MESSAGECODE_DAL_LOGINFO_7 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 7
#define ATI_MESSAGECODE_DAL_LOGINFO_8 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 8
#define ATI_MESSAGECODE_DAL_LOGINFO_9 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 9
#define ATI_MESSAGECODE_DAL_LOGINFO_10 \
            ATI_MESSAGECODE_TYPE_LOGINFO | ATI_MESSAGECODE_COMPONENT_DAL | 10

#define CODEPATH_DALMV7_DALActivateMacrovision_SUCCESS          0x00000001
#define CODEPATH_DALMV7_DALActivateMacrovision_FAIL             0x00000002
#define CODEPATH_DALMV7_DALSetMacrovisionMode_SUCCESS           0x00000004
#define CODEPATH_DALMV7_DALSetMacrovisionMode_FAIL              0x00000008
#define CODEPATH_DALMV7_DALDeactivateMacrovision_SUCCESS        0x00000010
#define CODEPATH_DALMV7_DALDeactivateMacrovision_FAIL           0x00000020
#define CODEPATH_DALMV7_DALValidateMVKey_SUCCESS                0x00000040
#define CODEPATH_DALMV7_DALValidateMVKey_FAIL                   0x00000080
#define CODEPATH_DALMV7_EXIT_POINT_1                            0x80000000
#define CODEPATH_DALMV7_EXIT_POINT_2                            0x40000000
#define CODEPATH_DALMV7_EXIT_POINT_3                            0x20000000
#define CODEPATH_DALMV7_EXIT_POINT_4                            0x10000000
#define CODEPATH_DALMV7_EXIT_POINT_5                            0x08000000
#define CODEPATH_DALMV7_EXIT_POINT_6                            0x04000000
#define CODEPATH_DALMV7_EXIT_POINT_7                            0x02000000
#define CODEPATH_DALMV7_EXIT_POINT_8                            0x01000000

typedef struct tagLogInfoParam
{
  ULONG       ulNumOfParams; 
  ULONG       ulParams[1]; 
} LOGINFOPARAM; 

// Note: The above definitions are for MV7 Log Information usage only !!!
// ---------------------------------------------------------------------------

#endif

