/*
	Copyright (c) Microsoft Corporation.  All rights reserved.
*/

/*
    This file declares the driver entry points.
*/

/*noscan*/ extern DRIVER_INITIALIZE DriverEntry;

#ifdef fun_IRP_MJ_CREATE
extern DRIVER_DISPATCH fun_IRP_MJ_CREATE; /*SAL:IRP_MJ_CREATE*/
#endif

#ifdef fun_IRP_MJ_CREATE_NAMED_PIPE
extern DRIVER_DISPATCH fun_IRP_MJ_CREATE_NAMED_PIPE; /*SAL:IRP_MJ_CREATE_NAMED_PIPE*/
#endif

#ifdef fun_IRP_MJ_CLOSE
extern DRIVER_DISPATCH fun_IRP_MJ_CLOSE; /*SAL:IRP_MJ_CLOSE*/
#endif

#ifdef fun_IRP_MJ_READ
extern DRIVER_DISPATCH fun_IRP_MJ_READ; /*SAL:IRP_MJ_READ*/
#endif

#ifdef fun_IRP_MJ_WRITE
extern DRIVER_DISPATCH fun_IRP_MJ_WRITE; /*SAL:IRP_MJ_WRITE*/
#endif

#ifdef fun_IRP_MJ_QUERY_INFORMATION
extern DRIVER_DISPATCH fun_IRP_MJ_QUERY_INFORMATION; /*SAL:IRP_MJ_QUERY_INFORMATION*/
#endif

#ifdef fun_IRP_MJ_SET_INFORMATION
extern DRIVER_DISPATCH fun_IRP_MJ_SET_INFORMATION; /*SAL:IRP_MJ_SET_INFORMATION*/
#endif

#ifdef fun_IRP_MJ_QUERY_EA
extern DRIVER_DISPATCH fun_IRP_MJ_QUERY_EA; /*SAL:IRP_MJ_QUERY_EA*/
#endif

#ifdef fun_IRP_MJ_SET_EA
extern DRIVER_DISPATCH fun_IRP_MJ_SET_EA; /*SAL:IRP_MJ_SET_EA*/
#endif

#ifdef fun_IRP_MJ_FLUSH_BUFFERS
extern DRIVER_DISPATCH fun_IRP_MJ_FLUSH_BUFFERS; /*SAL:IRP_MJ_FLUSH_BUFFERS*/
#endif

#ifdef fun_IRP_MJ_QUERY_VOLUME_INFORMATION
extern DRIVER_DISPATCH fun_IRP_MJ_QUERY_VOLUME_INFORMATION; /*SAL:IRP_MJ_QUERY_VOLUME_INFORMATION*/
#endif

#ifdef fun_IRP_MJ_SET_VOLUME_INFORMATION
extern DRIVER_DISPATCH fun_IRP_MJ_SET_VOLUME_INFORMATION; /*SAL:IRP_MJ_SET_VOLUME_INFORMATION*/
#endif

#ifdef fun_IRP_MJ_DIRECTORY_CONTROL
extern DRIVER_DISPATCH fun_IRP_MJ_DIRECTORY_CONTROL; /*SAL:IRP_MJ_DIRECTORY_CONTROL*/
#endif

#ifdef fun_IRP_MJ_FILE_SYSTEM_CONTROL
extern DRIVER_DISPATCH fun_IRP_MJ_FILE_SYSTEM_CONTROL; /*SAL:IRP_MJ_FILE_SYSTEM_CONTROL*/
#endif

#ifdef fun_IRP_MJ_DEVICE_CONTROL
extern DRIVER_DISPATCH fun_IRP_MJ_DEVICE_CONTROL; /*SAL:IRP_MJ_DEVICE_CONTROL*/
#endif

#ifdef fun_IRP_MJ_INTERNAL_DEVICE_CONTROL
extern DRIVER_DISPATCH fun_IRP_MJ_INTERNAL_DEVICE_CONTROL; /*SAL:IRP_MJ_INTERNAL_DEVICE_CONTROL*/
#endif

#ifdef fun_IRP_MJ_SHUTDOWN
extern DRIVER_DISPATCH fun_IRP_MJ_SHUTDOWN; /*SAL:IRP_MJ_SHUTDOWN*/
#endif

#ifdef fun_IRP_MJ_LOCK_CONTROL
extern DRIVER_DISPATCH fun_IRP_MJ_LOCK_CONTROL; /*SAL:IRP_MJ_LOCK_CONTROL*/
#endif

#ifdef fun_IRP_MJ_CLEANUP
extern DRIVER_DISPATCH fun_IRP_MJ_CLEANUP; /*SAL:IRP_MJ_CLEANUP*/
#endif

#ifdef fun_IRP_MJ_CREATE_MAILSLOT
extern DRIVER_DISPATCH fun_IRP_MJ_CREATE_MAILSLOT; /*SAL:IRP_MJ_CREATE_MAILSLOT*/
#endif

#ifdef fun_IRP_MJ_QUERY_SECURITY
extern DRIVER_DISPATCH fun_IRP_MJ_QUERY_SECURITY; /*SAL:IRP_MJ_QUERY_SECURITY*/
#endif

#ifdef fun_IRP_MJ_SET_SECURITY
extern DRIVER_DISPATCH fun_IRP_MJ_SET_SECURITY; /*SAL:IRP_MJ_SET_SECURITY*/
#endif

#ifdef fun_IRP_MJ_POWER
extern DRIVER_DISPATCH fun_IRP_MJ_POWER; /*SAL:IRP_MJ_POWER*/
#endif

#ifdef fun_IRP_MJ_SYSTEM_CONTROL
extern DRIVER_DISPATCH fun_IRP_MJ_SYSTEM_CONTROL; /*SAL:IRP_MJ_SYSTEM_CONTROL*/
#endif

#ifdef fun_IRP_MJ_DEVICE_CHANGE
extern DRIVER_DISPATCH fun_IRP_MJ_DEVICE_CHANGE; /*SAL:IRP_MJ_DEVICE_CHANGE*/
#endif

#ifdef fun_IRP_MJ_QUERY_QUOTA
extern DRIVER_DISPATCH fun_IRP_MJ_QUERY_QUOTA; /*SAL:IRP_MJ_QUERY_QUOTA*/
#endif

#ifdef fun_IRP_MJ_SET_QUOTA
extern DRIVER_DISPATCH fun_IRP_MJ_SET_QUOTA; /*SAL:IRP_MJ_SET_QUOTA*/
#endif

#ifdef fun_IRP_MJ_PNP
extern DRIVER_DISPATCH fun_IRP_MJ_PNP; /*SAL:IRP_MJ_PNP*/
#endif

#ifdef fun_IRP_MJ_PNP_POWER
extern DRIVER_DISPATCH fun_IRP_MJ_PNP_POWER; /*SAL:IRP_MJ_PNP_POWER*/
#endif

#ifdef fun_IRP_MJ_SCSI
extern DRIVER_DISPATCH fun_IRP_MJ_SCSI; /*SAL:IRP_MJ_SCSI*/
#endif

#ifdef fun_IRP_MJ_OTHER
extern DRIVER_DISPATCH fun_IRP_MJ_OTHER; /*SAL:IRP_MJ_OTHER*/
#endif

#ifdef fun_DriverStartIo
extern DRIVER_STARTIO fun_DriverStartIo;
#endif

#ifdef fun_AddDevice
extern DRIVER_ADD_DEVICE fun_AddDevice;
#endif

#ifdef fun_DriverUnload
extern DRIVER_UNLOAD fun_DriverUnload;
#endif
